### Exercise 1: Create a Numpy array (from a list)

In [38]:
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)

In [39]:
type(array1)

numpy.ndarray

In [40]:
type(lst1)

list

### Exercise 2: Add two Numpy arrays

In [41]:
lst2 = lst1 + lst1
print(lst2)
array2 = array1 + array1
print(array2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


### Exercise 3: Mathematical operations on Numpy arrays

In [42]:
print("array1 multiplied by array1: ",array1*array1)
print("array1 divided by array1: ",array1/array1)
print("array1 raised to the power of array1: ",array1**array1)

array1 multiplied by array1:  [1 4 9]
array1 divided by array1:  [1. 1. 1.]
array1 raised to the power of array1:  [ 1  4 27]


### Exercise 4: More advanced mathematical operations on Numpy arrays

In [43]:
lst_5=[i for i in range(1,6)]
print(lst_5)
array_5=np.array(lst_5)
# sine function
print("Sine: ",np.sin(array_5))
# logarithm
print("Natural logarithm: ",np.log(array_5))
print("Base-10 logarithm: ",np.log10(array_5))
print("Base-2 logarithm: ",np.log2(array_5))
# Exponential
print("Exponential: ",np.exp(array_5))

[1, 2, 3, 4, 5]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Base-10 logarithm:  [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Base-2 logarithm:  [0.         1.         1.5849625  2.         2.32192809]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### Exercise 5: How to generate arrays easily? `arange` and `linspace`

In [44]:
print("A series of numbers:",np.arange(5,16))
print("Numbers spaced apart by 2:",np.arange(0,11,2))
print("Numbers spaced apart by float:",np.arange(0,11,2.5))
print("Every 5th number from 30 in reverse order: ",np.arange(30,-1,-5))
print("11 linearly spaced numbers between 1 and 5: ",np.linspace(1,5,11))

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]
Numbers spaced apart by 2: [ 0  2  4  6  8 10]
Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]
Every 5th number from 30 in reverse order:  [30 25 20 15 10  5  0]
11 linearly spaced numbers between 1 and 5:  [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


### Exercise 6: Creating multi-dimensional array

In [45]:
list_2D = [[1,2,3],[4,5,6],[7,8,9]]
mat1 = np.array(list_2D)
print("Type/Class of this object:",type(mat1))
print("Here is the matrix\n----------\n",mat1,"\n----------")

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------


In [46]:
tuple_2D = np.array([(1.5,2,3), (4,5,6)])
mat_tuple = np.array(tuple_2D)
print (mat_tuple)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


### Exercise 7: Dimension, shape, size, and data type of the 2D array

In [47]:
print("Dimension of this matrix: ",mat1.ndim,sep='') 
print("Size of this matrix: ", mat1.size,sep='') 
print("Shape of this matrix: ", mat1.shape,sep='')
print("Data type of this matrix: ", mat1.dtype,sep='')

Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


### Exercise 8: Zeros, Ones, Random, and Identity Matrices and Vectors

In [48]:
print("Vector of zeros: ",np.zeros(5))
print("Matrix of zeros: ",np.zeros((3,4)))
print("Vector of ones: ",np.ones(4))
print("Matrix of ones: ",np.ones((4,2)))
print("Matrix of 5’s: ",5*np.ones((3,3)))
print("Identity matrix of dimension 2:",np.eye(2))
print("Identity matrix of dimension 4:",np.eye(4))
print("Random matrix of shape (4,3):\n",np.random.randint(low=1,high=10,size=(4,3)))

Vector of zeros:  [0. 0. 0. 0. 0.]
Matrix of zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Vector of ones:  [1. 1. 1. 1.]
Matrix of ones:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5’s:  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Identity matrix of dimension 2: [[1. 0.]
 [0. 1.]]
Identity matrix of dimension 4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random matrix of shape (4,3):
 [[2 6 1]
 [9 1 1]
 [8 7 2]
 [7 6 9]]


### Exercise 9: Reshaping, Ravel, Min, Max, Sorting

In [49]:
a = np.random.randint(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [50]:
print("\na looks like\n",a)
print("\nb looks like\n",b)
print("\nc looks like\n",c)


a looks like
 [ 3 94 42 63 68 39 68 65 61 31 74 19 94  6 96 15  8 15 56 21 95 66 96 60
  3 41 31 73 78 52]

b looks like
 [[[ 3 94 42 63 68]
  [39 68 65 61 31]
  [74 19 94  6 96]]

 [[15  8 15 56 21]
  [95 66 96 60  3]
  [41 31 73 78 52]]]

c looks like
 [[ 3 94 42 63 68]
 [39 68 65 61 31]
 [74 19 94  6 96]
 [15  8 15 56 21]
 [95 66 96 60  3]
 [41 31 73 78 52]]


In [51]:
b_flat = b.ravel()
print(b_flat)

[ 3 94 42 63 68 39 68 65 61 31 74 19 94  6 96 15  8 15 56 21 95 66 96 60
  3 41 31 73 78 52]


### Exercise 10: Indexing and slicing

In [52]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr2 = np.arange(0,21,2)
print("New array:",arr2)
print("Elements at 2nd, 4th, and 9th index are:", arr2[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [53]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)

print("\nDouble bracket indexing\n")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
 [[89 12 21 92 74]
 [91 94 56 89 93]
 [39 49 58 92 63]]

Double bracket indexing

Element in row index 1 and column index 2: 56

Single bracket with comma indexing

Element in row index 1 and column index 2: 56

Row or column extract

Entire row at index 2: [39 49 58 92 63]
Entire column at index 3: [92 89 92]

Subsetting sub-matrices

Matrix with row indices 1 and 2 and column indices 3 and 4
 [[89 93]
 [92 63]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[12 92]
 [94 89]]


### Exercise 11: Conditional subsetting

In [54]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)
print ("\nElements greater than 50\n", mat[mat>50])

Matrix of random 2-digit numbers
 [[21 16 77 31 81]
 [21 50 62 67 14]
 [33 94 52 39 18]]

Elements greater than 50
 [77 81 62 67 94 52]


### Exercise 12: Array operations (array-array, array-scalar, universal functions)

In [55]:
mat1 = np.random.randint(1,10,9).reshape(3,3)
mat2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n",mat2)

print("\nAddition\n", mat1+mat2)
print("\nMultiplication\n", mat1*mat2)
print("\nDivision\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n", 3*mat1-2*mat2)

print("\nAddition of a scalar (100)\n", 100+mat1)

print("\nExponentiation, matrix cubed here\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
 [[1 6 5]
 [6 2 2]
 [5 3 5]]

2nd Matrix of random single-digit numbers
 [[9 7 5]
 [3 9 8]
 [8 8 9]]

Addition
 [[10 13 10]
 [ 9 11 10]
 [13 11 14]]

Multiplication
 [[ 9 42 25]
 [18 18 16]
 [40 24 45]]

Division
 [[0.11111111 0.85714286 1.        ]
 [2.         0.22222222 0.25      ]
 [0.625      0.375      0.55555556]]

Lineaer combination: 3*A - 2*B
 [[-15   4   5]
 [ 12 -12 -10]
 [ -1  -7  -3]]

Addition of a scalar (100)
 [[101 106 105]
 [106 102 102]
 [105 103 105]]

Exponentiation, matrix cubed here
 [[  1 216 125]
 [216   8   8]
 [125  27 125]]

Exponentiation, sq-root using pow function
 [[1.         2.44948974 2.23606798]
 [2.44948974 1.41421356 1.41421356]
 [2.23606798 1.73205081 2.23606798]]


### Stacking arrays

In [56]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("Matrix a\n",a)
print("Matrix b\n",b)
print("Vertical stacking\n",np.vstack((a,b)))
print("Horizontal stacking\n",np.hstack((a,b)))

Matrix a
 [[1 2]
 [3 4]]
Matrix b
 [[5 6]
 [7 8]]
Vertical stacking
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stacking
 [[1 2 5 6]
 [3 4 7 8]]
